### ISSUE TITLE
Add helpful error message when `assert basem` fails

### ISSUE THREAD

**Issue by ianhi** [asottile/setup-cfg-fmt#95]
https://github.com/asottile/setup-cfg-fmt/blob/8b497a9a7036a9589395e5c128bece2c7990cc45/setup_cfg_fmt.py#L259-L261 can fail with error that I'm finding hard to interpret. For example running this on https://github.com/ianhi/mpl-interactions/blob/0.18.0/setup.cfg fails with the below error and it's not clear to me how to fix it.

```python
Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/mpl-dev/bin/setup-cfg-fmt", line 8, in <module>
    sys.exit(main())
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 502, in main
    if format_file(
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 412, in format_file
    group_requires = _requires(cfg, key, 'options.extras_require')
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 220, in _requires
    normalized = sorted(
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 221, in <genexpr>
    (_normalize_req(req) for req in require_group),
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 230, in _normalize_req
    normalized = _normalize_lib(lib)
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 244, in _normalize_lib
    base = _req_base(lib)
  File "/home/ian/mambaforge/envs/mpl-dev/lib/python3.9/site-packages/setup_cfg_fmt.py", line 261, in _req_base
    assert basem
AssertionError
```

**Comment by asottile** [comment]
[substitution hacks](https://github.com/ianhi/mpl-interactions/blob/a4829c95fb6f0415633e092368615e265d28eb25/setup.cfg#L47) are not portable, allowed, or supported

**Comment by ianhi** [comment]
Hi @asottile thanks for the information I didn't know that. I appreciate the pointer on what was wrong but what I'm trying to suggest is to have something like this:

```python
if not basem:
   raise ValueError(f"Library {lib} is invalid")
```

or something more verbose so that users (i.e. me) have a hint as to where to start looking to fix things.

**Comment by asottile** [comment]
are you interested in sending a patch?

**Comment by ianhi** [comment]
Happy to, when I opened I wasn't totally clear what was happening - now that I understand will do.
